apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    app: unseal-sample
    part-of: unseal-sample
  name: unseal-sample
spec:
  replicas: 2
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
