---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - unsealer.amoyel.fr
  resources:
  - unseals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unsealer.amoyel.fr
  resources:
  - unseals/finalizers
  verbs:
  - update
- apiGroups:
  - unsealer.amoyel.fr
  resources:
  - unseals/status
  verbs:
  - get
  - patch
  - update
