# permissions for end users to edit unseals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unseal-editor-role
rules:
- apiGroups:
  - unsealer.amoyel.fr
  resources:
  - unseals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unsealer.amoyel.fr
  resources:
  - unseals/status
  verbs:
  - get
