apiVersion: unsealer.amoyel.fr/v1alpha1
kind: Unseal
metadata:
  name: unseal-sample
  namespace: vault-unsealer-operator-system
spec:
  vaultNodes:
    - https://vault-cluster-node-url-1:8200
    - https://vault-cluster-node-url-2:8200
    - https://vault-cluster-node-url-3:8200
  thresholdKeysSecret: thresholdkeys
  # Optional, but important if you have internal pki for your vault certificate. Secret need to be in the same namespace as this resource
  caCertSecret: cacertificate
  # Optional, set this parameter to true if you want to skip tls certificate verification
  tlsSkipVerify: false
  # Optional
  retryCount: 3